### ISSUE TITLE
Undefined method error

### ISSUE THREAD

**Issue by citrus** [mattgreen/elevate#9]
I'm getting the following error when trying to use elevate:

``` text
2013-07-08 12:46:04.108 ExampleApp[29827:1b03] user.rb:12:in `block in authenticate!:': undefined method `post' for Elevate::HTTP:Class (NoMethodError)
    from operation.rb:50:in `main'
```

And the code:

``` ruby
def authenticate!(username, password)
  @authenticate_task = async username: username, password: password do
    task do
      response = Elevate::HTTP.post("http://example.com/api/sessions.json", username: @username, password: @password)
      puts "response: "
      puts response.inspect
    end
    on_start do
      puts "requesting.."
    end    
    on_finish do |result, exception|
      puts "complete.."
      puts result.inspect
    end
  end
end
```

What's really strange is rubymotion seems to be renaming classes inside the HTTP namespace... for example this fails:

``` text
(main)> Elevate::HTTP::Request::METHODS
2013-07-08 12:56:02.128 ExampleApp[30165:c07] uninitialized constant Elevate::HTTP::Request (NameError)
=> #<NameError: uninitialized constant Elevate::HTTP::Request>
```

But this works:

``` text
(main)> Elevate::HTTP::HTTPRequest::METHODS
=> [:get, :post, :put, :delete, :patch, :head, :options]
```

Any ideas?

Thanks!! :beer:

**Comment by mattgreen** [comment]
What version are you using? I have not actually pushed 0.6.0, though the docs are updated. I suspect you're using 0.5.x. You can pull from git in the meantime.

**Comment by citrus** [comment]
I'm using 0.5.0 with bundler and the latest release of rubymotion. I'll try using the repo instead, thanks.

**Comment by mattgreen** [comment]
Hope it fixes it for you. If not, chime in. :)

**Comment by citrus** [comment]
That worked :) Thanks again! :beers:
